apiVersion: v1
kind: Service
metadata:
  name: event-subscriber-0
  namespace: eventing-test
spec:
  type: ClusterIP
  selector:
    app: event-subscriber-0
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: event-subscriber-1
  namespace: eventing-test
spec:
  type: ClusterIP
  selector:
    app: event-subscriber-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: event-subscriber-2
  namespace: eventing-test
spec:
  type: ClusterIP
  selector:
    app: event-subscriber-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
