apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadtest-subscriber-0
  name: loadtest-subscriber-0
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-subscriber-0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadtest-subscriber-0
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: eventing
                app.kubernetes.io/name: controller
            namespaces:
            - kyma-system
            topologyKey: kubernetes.io/hostname
      containers:
        - image: docker.io/muralov/loadtest-local-subscriber:v3
          imagePullPolicy: IfNotPresent
          name: loadtest-subscriber
          command: ["local-subscriber"]
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadtest-subscriber-1
  name: loadtest-subscriber-1
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-subscriber-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadtest-subscriber-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: eventing
                app.kubernetes.io/name: controller
            namespaces:
            - kyma-system
            topologyKey: kubernetes.io/hostname
      containers:
        - image: docker.io/muralov/loadtest-local-subscriber:v3
          imagePullPolicy: IfNotPresent
          name: local-subscriber
          command: ["local-subscriber"]
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
