apiVersion: v1
kind: ConfigMap
metadata:
  name: loadtest-publisher
  namespace: eventing-test
data:
  publish_endpoint: "http://eventing-publisher-proxy.kyma-system"
  use_legacy_events:  "false"
  event_source: "noapp"
  version_format: "v%04d"
  max_inflight_messages_0: "10"
  max_inflight_messages_1: "10"
  event_name_0: "order.created"
  event_name_1: "order.updated"
  generate_count_0: "1"
  generate_count_1: "1"
  eps_start_0: "1"
  eps_start_1: "1"
  eps_increment_0: "1"
  eps_increment_1: "1"
  eps_limit: "2000"
  workers: "12"
  max_idle_conns: "100"
  max_conns_per_host: "100"
  max_idle_conns_per_host: "100"
  idle_conn_timeout: "1m0s"
