apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadtest-publisher
  namespace: eventing-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadtest-publisher
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - eventing.kyma-project.io
    resources:
      - subscriptions
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loadtest-publisher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loadtest-publisher
subjects:
  - kind: ServiceAccount
    name: loadtest-publisher
    namespace: eventing-test
---
