apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: publisher
  name: publisher
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - image: ghcr.io/kyma-project/eventing-tools:0.0.3
          args:
            - publisher
          imagePullPolicy: IfNotPresent
          name: publisher
          env:
            - name: SERVER_ADDRESS
              value: ":8888"
            - name: PUBLISH_ENDPOINT_CLOUDEVENTS
              value: "http://eventing-publisher-proxy.kyma-system/publish"
            - name: PUBLISH_ENDPOINT_LEGACY_EVENTS
              value: "http://eventing-publisher-proxy.kyma-system/%s/v1/events"
            - name: PUBLISH_INTERVAL
              value: "3s"
            - name: EVENT_SOURCE
              value: "/default/sap.kyma/tunas-develop"
            - name: EVENT_TYPE_PREFIX
              value: "sap.kyma.custom"
            - name: MAX_IDLE_CONNS
              value: "10"
            - name: MAX_CONNS_PER_HOST
              value: "10"
            - name: MAX_IDLE_CONNS_PER_HOST
              value: "10"
            - name: IDLE_CONN_TIMEOUT
              value: "1m0s"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-subscriber-0
  name: event-subscriber-0
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-subscriber-0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-subscriber-0
    spec:
      containers:
        - image: ghcr.io/kyma-project/eventing-tools:0.0.3 
          args:
            - subscriber
            - --listen-port=8888
          imagePullPolicy: IfNotPresent
          name: event-subscriber
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-subscriber-1
  name: event-subscriber-1
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-subscriber-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-subscriber-1
    spec:
      containers:
        - image: ghcr.io/kyma-project/eventing-tools:0.0.3 
          args:
            - subscriber
            - --listen-port=8888
          imagePullPolicy: IfNotPresent
          name: event-subscriber
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-subscriber-2
  name: event-subscriber-2
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-subscriber-2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-subscriber-2
    spec:
      containers:
        - image: ghcr.io/kyma-project/eventing-tools:0.0.3 
          args:
            - subscriber
            - --listen-port=8888
          imagePullPolicy: IfNotPresent
          name: event-subscriber
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
---
