apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-0
  namespace: eventing-test
  labels:
    app.kubernetes.io/name: function-0
spec:
  replicas: 1
  resourceConfiguration:
    function:
      profile: XS
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
  runtime: nodejs16
  scaleConfig:
    maxReplicas: 5
    minReplicas: 1
  source:
    inline:
      source: |-
        module.exports = {
          main: function (event, context) {
            let data = JSON.stringify(event.data);
            console.log(data);
            return data
          }
        }
---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-1
  namespace: eventing-test
  labels:
    app.kubernetes.io/name: function-1
spec:
  replicas: 1
  resourceConfiguration:
    function:
      profile: XS
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
  runtime: nodejs16
  scaleConfig:
    maxReplicas: 5
    minReplicas: 1
  source:
    inline:
      source: |-
        module.exports = {
          main: function (event, context) {
            let data = JSON.stringify(event.data);
            console.log(data);
            return data
          }
        }
---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-2
  namespace: eventing-test
  labels:
    app.kubernetes.io/name: function-2
spec:
  replicas: 1
  resourceConfiguration:
    function:
      profile: XS
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
  runtime: nodejs16
  scaleConfig:
    maxReplicas: 5
    minReplicas: 1
  source:
    inline:
      source: |-
        module.exports = {
          main: function (event, context) {
            let data = JSON.stringify(event.data);
            console.log(data);
            return data
          }
        }
---
